apiVersion: v1
kind: Pod
metadata:
  name: twenty-one-game
  labels:
    app: twenty-one-game
spec:
  containers:
    - name: twenty-one-game
      image: eu.gcr.io/ons-sdx-training/twenty-one-game:latest
      imagePullPolicy: Always
      env:
        - name: PYTHONUNBUFFERED
          value: "1"
      volumeMounts:
        - name: variables
          mountPath: /config
          readOnly: true
  volumes:
    - name: variables
      configMap:
        name: player-config-file
